extern int foo;
void print_foo();
void print1(int);
void print2(int,int);
void printd(double,double);
void swap_v(int,int);
void swap_r(int&,int&);
void swap_double_v(double, double);
void swap_double_r(double&, double&);
void swap_cr(const int& a, const int& b);
